# Phiên bản Docker Compose file với bảo mật tài khoản DB hơn
services:
  user-api:
    image: nashydawg/ex-user:latest
    # ports:
      # - "5000:5000"  # Không cần expose cổng ra ngoài(khi dung nginx làm reverse proxy thi an cai nay)
    depends_on:
      - db
    environment:
      # Kết nối dùng User/Pass đã khai báo
      - MONGO_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@db:27017/${MONGO_DB_NAME}?authSource=admin
      - REDIS_URL=redis://redis:6379
    restart: always
    networks:
      - devops-net # Kết nối vào mạng chung (khi dung nginx làm reverse proxy thi dung cai nay)

  db:
    image: mongo:latest
    environment:
      # Thiết lập tài khoản Admin cho MongoDB khi khởi tạo lần đầu
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine

  # Cấu hình Nginx làm reverse proxy (dung nginx thi them nginx va network)
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - user-api
    networks:
      - devops-net
    restart: always

networks:
  devops-net: # Khai báo mạng chung
    driver: bridge

volumes:
  mongodb_data:







