# Phiên bản Docker Compose file với bảo mật tài khoản DB hơn
services:
  user-api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      # Kết nối dùng User/Pass đã khai báo
      - MONGO_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@db:27017/${MONGO_DB_NAME}?authSource=admin
      - REDIS_URL=redis://redis:6379
    restart: always

  db:
    image: mongo:latest
    environment:
      # Thiết lập tài khoản Admin cho MongoDB khi khởi tạo lần đầu
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine

volumes:
  mongodb_data:







